export const IGDB_GENRES: readonly string[] = [
  'Adventure',
  'Arcade',
  'Card & Board Game',
  'Fighting',
  "Hack and slash/Beat 'em up",
  'Indie',
  'MOBA',
  'Music',
  'Pinball',
  'Platform',
  'Point-and-click',
  'Puzzle',
  'Quiz/Trivia',
  'Racing',
  'Real Time Strategy (RTS)',
  'Role-playing (RPG)',
  'Shooter',
  'Simulator',
  'Sport',
  'Strategy',
  'Tactical',
  'Turn-based strategy (TBS)',
  'Visual Novel'
];
